- name: SSH into EC2 and run app

  on:
    push:
      branches:
        - develop
        -
  uses: appleboy/ssh-action@v0.1.6
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      echo "🔻 Killing existing app screen session if exists..."
      screen -S springboot -X quit || echo "No existing screen session"
      
      echo "🚀 Starting new screen session for Spring Boot app..."
      screen -dmS springboot java -jar /home/ubuntu/PerbaikiinAja-0.0.1-SNAPSHOT.jar
      
      sleep 3
      echo "✅ Checking if Spring Boot app is running inside screen..."
      screen -ls | grep springboot && echo "App is running in screen!" || echo "⚠️ Failed to start app"
